#ifndef ASSETS_TYPES_H
#define ASSETS_TYPES_H

typedef enum AssetType{
    ASSET_TYPE_NONE,
    ASSET_TYPE_MODEL,
    ASSET_TYPE_IMG,
    ASSET_TYPE_SOUND,
    ASSET_TYPE_FONT,
    ASSET_TYPE_TEXT
}AssetType;

#endif /* ASSETS_TYPES_H */